import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com").strip()
SMTP_PORT_STR = os.getenv("SMTP_PORT", "587").strip()
SMTP_PORT = int(SMTP_PORT_STR) if SMTP_PORT_STR.isdigit() else 587
SMTP_USERNAME = os.getenv("SMTP_USERNAME", "").strip().strip('"').strip("'")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "").strip().strip('"').strip("'")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "").strip().strip('"').strip("'")

def send_alert_email(subject: str, body_html: str, recipient: str = None):
    # Default to ADMIN_EMAIL if no recipient specified
    target_email = recipient if recipient else ADMIN_EMAIL
    
    if not SMTP_USERNAME or not SMTP_PASSWORD or not target_email:
        print(f"⚠️ SMTP credentials or target email ({target_email}) missing. Skipping dispatch.")
        return False
        
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"EduMitra Alerts <{SMTP_USERNAME}>"
        msg["To"] = target_email

        part = MIMEText(body_html, "html")
        msg.attach(part)

        # Connect to server and send
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(SMTP_USERNAME, target_email, msg.as_string())
        
        print(f"✅ Alert email sent to {target_email}")
        return True
    except Exception as e:
        print(f"❌ Failed to send email to {target_email}: {e}")
        return False

def send_high_risk_alert(student_name: str, usn: str, avg_exam: float, avg_att: float, risk_details: dict, student_email: str = None):
    subject = f"[EduMitra Alert] High Risk Academic Warning: {student_name}"
    
    # Send to student primarily, or admin if student email is missing
    target = student_email if student_email else ADMIN_EMAIL
    
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #FF4757;">⚠️ High Risk Student Alert</h2>
        <p>The EduMitra monitoring system has identified a student requiring immediate academic intervention.</p>
        <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
          <tr>
            <th style="text-align: left; border-bottom: 2px solid #eee; padding: 8px;">Metric</th>
            <th style="text-align: left; border-bottom: 2px solid #eee; padding: 8px;">Value</th>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Name</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{student_name}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>USN</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{usn}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Average Exam Score</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; color: {'#FF4757' if avg_exam < 50 else '#FFA502'};">{avg_exam}%</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Average Attendance</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; color: {'#FF4757' if avg_att < 50 else '#FFA502'};">{avg_att}%</td>
          </tr>
        </table>
        
        <h3>ML Risk Breakdown</h3>
        <p><strong>Overall Prediction:</strong> {risk_details.get('risk_level', 'Unknown')}</p>
        <ul>
        """
        
    if "probabilities" in risk_details:
        for k, v in risk_details["probabilities"].items():
            html += f"<li>{k}: {v}%</li>"
            
    html += """
        </ul>
        <p>Please log in to the EduMitra Admin Dashboard to review their full academic profile and initiate an intervention roadmap.</p>
        <br>
        <p style="font-size: 12px; color: #888;">This is an automated message generated by the EduMitra Monitoring System.</p>
      </body>
    </html>
    """
    
    return send_alert_email(subject, html, target)

def send_admin_welcome_alert(admin_name: str, admin_email: str):
    subject = f"Welcome to EduMitra, {admin_name}! 👋"
    
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
          <h2 style="color: #6C63FF; text-align: center;">Welcome to EduMitra!</h2>
          <p>Hi <strong>{admin_name}</strong>,</p>
          <p>Your administrator account has been successfully created. You can now log in and start monitoring student performance across your departments.</p>
          
          <div style="background: #f9f9f9; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>What's Next?</strong></p>
            <ul style="margin: 10px 0 0 0; padding-left: 20px;">
              <li>Add students to the system.</li>
              <li>Input academic records and attendance.</li>
              <li>Monitor high-risk alerts and classification charts.</li>
            </ul>
          </div>
          
          <p>If you didn't create this account, please ignore this email or contact support.</p>
          <br>
          <p>Best Regards,<br><strong>The EduMitra Team</strong></p>
        </div>
        <p style="font-size: 11px; color: #888; text-align: center; margin-top: 20px;">This is an automated notification from the EduMitra System.</p>
      </body>
    </html>
    """
    
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"EduMitra Team <{SMTP_USERNAME}>"
        msg["To"] = admin_email
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(SMTP_USERNAME, admin_email, msg.as_string())
        
        print(f"✅ Welcome email sent to {admin_email}")
        return True
    except Exception as e:
        print(f"❌ Failed to send welcome email: {e}")
        return False
